name: My First Workflow for Java

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        repository: ${{ github.repository }} # Default repository
        ref: main # Branch to checkout, replace with your branch if different
        token: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication
        fetch-depth: 1 # Fetch only the latest commit
